package me.kevinkang.waittime.firebase;

import me.kevinkang.waittime.model.Restaurant;

/**
 * Created by kevink97 on 1/14/17.
 */

public class FBRestaurant implements Restaurant {
    private final String UID;
    private int popularity;
    private String description;
    private double rating;
    private String name;

    /**
     * Sets FBRestaurant with its unique ID From firebase, and the name of the restaurant.
     *
     * @param UID UID of Restaurant generated by Firebase
     * @param name name of restaurant. Cannot be empty
     */
    public FBRestaurant(String UID, String name) {
        this.UID = UID;
        this.popularity = 0;
        this.description = "";
        this.rating = -1;
        this.name = name;
    }

    /**
     * gets UID of Restaurant
     *
     * @return UID of restaurants
     */
    @Override
    public String getUID() {
        return this.UID;
    }

    /**
     * gets name of Restaurant
     *
     * @return name of restaurants
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Sets popularity of Restaurant.
     * Popularity is set by the amount of check in.
     *
     * @param newPopularity popularity of restaurant
     */
    @Override
    public void setPopularity(int newPopularity) {
        this.popularity = newPopularity;
    }

    /**
     * gets the popularity of Restaurant
     *
     * @return popularity of Restaurant
     */
    @Override
    public int getPopularity() {
        return this.popularity;
    }

    /**
     * sets the description of Restaurant
     *
     * @param newDescription new description for restaurant
     */
    @Override
    public void setDescription(String newDescription) {
        this.description = newDescription;
    }

    /**
     * gets the description of Restaurant
     *
     * @return description of restaurant
     */
    @Override
    public String getDescription() {
        return this.description;
    }

    /**
     * sets Rating of the Restaurant
     *
     * @param newRating new rating for restaurant
     */
    @Override
    public void setRating(double newRating) {
        this.rating = newRating;
    }

    /**
     * gets Rating for restuarant
     *
     * @return rating for restaurant
     */
    @Override
    public double getRating() {
        return this.rating;
    }
}
